### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'node_modules/tensorflow/src/interop/libtensorflow.so'

### ISSUE THREAD

**Issue by tomasgvivo** [nikhilk/node-tensorflow#11]
So i'm trying to use this module.. but, when I execute the demo, this error is shown.

```
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'node_modules/tensorflow/src/interop/libtensorflow.so'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at fs.readFileSync (fs.js:508:33)
    at new DynamicLibrary (node_modules/ffi/lib/dynamic_library.js:67:21)
    at Object.Library (node_modules/ffi/lib/library.js:45:12)
    at Library.create (node_modules/tensorflow/src/interop/ffiplus.js:29:17)
    at Object.<anonymous> (node_modules/tensorflow/src/interop/libtensorflow.js:158:7)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

**Comment by gutsal-arsen** [comment]
+1 same thing

**Comment by gutsal-arsen** [comment]
Well @tomasgvivo  seems issue#3 explain the solution

**Comment by nikhilk** [comment]
Closing this out in favor of #15.
